import { isKnownType } from '../lib/fields';

export const rootPersonFields = [
  {
    name: 'id',
    label: 'ID',
    type: 'I',
    read_only: true,
    required: false,
    custom_field: false,
  },
  {
    name: 'email',
    label: 'Email Address',
    type: 'EmailField',
    read_only: false,
    required: true,
    custom_field: false,
  },
  {
    name: 'first_name',
    label: 'First Name',
    type: 'S',
    read_only: false,
    required: true,
    custom_field: false,
  },
  {
    name: 'last_name',
    label: 'Last Name',
    type: 'S',
    read_only: false,
    required: true,
    custom_field: false,
  },
  {
    name: 'account',
    label: null,
    type: 'R',
    read_only: false,
    required: false,
    custom_field: false,
  },
  {
    name: 'created_at',
    label: null,
    type: 'DT',
    read_only: true,
    required: false,
    custom_field: false,
  },
  {
    name: 'updated_at',
    label: null,
    type: 'DT',
    read_only: true,
    required: false,
    custom_field: false,
  },
  {
    name: 'archived',
    label: null,
    type: 'BooleanField',
    read_only: false,
    required: false,
    custom_field: false,
  },
  {
    name: 'ext_system_id',
    label: null,
    type: 'I',
    read_only: false,
    required: false,
    custom_field: false,
  },
  {
    name: 'ext_id',
    label: null,
    type: 'S',
    read_only: false,
    required: false,
    custom_field: false,
  },
  {
    name: 'date_of_birth',
    label: 'Date of birth',
    type: 'D',
    read_only: false,
    required: true,
    custom_field: true,
  },
  {
    name: 'phone',
    label: 'Phone Number',
    type: 'S',
    read_only: false,
    required: true,
    custom_field: true,
  },
];

export const filteredPersonFields = rootPersonFields.filter((f) => isKnownType(f));
